name: Release Drafter

on:
  push:
    # branches to consider in the event; optional, defaults to all
    branches:
      - master

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  linux-artifact:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Build LuaFormatter
      run: |
         git submodule update --init
         cmake -DCMAKE_BUILD_TYPE=Release
         make
    - uses: actions/upload-artifact@v2
      with:
        name: linux-artifact
        path: lua-format

  windows-artifact:
    runs-on: windows-latest
    steps:
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
    - uses: actions/checkout@v2
    - name: Build LuaFormatter
      run: |
         git submodule update --init
         cmake -G "Visual Studio 17 2022" -DCMAKE_BUILD_TYPE=Release
         msbuild "lua-formatter.sln" /p:Configuration=Release /p:Platform=x64 /clp:ErrorsOnly /target:Build
    - uses: actions/upload-artifact@v2
      with:
        name: windows-artifact
        path: Release/lua-format.exe

  darwin-artifact:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build LuaFormatter
      run: |
         git submodule update --init
         cmake -DCMAKE_BUILD_TYPE=Release
         make
    - uses: actions/upload-artifact@v2
      with:
        name: darwin-artifact
        path: lua-format
